server:
  port: 8081
  servlet:
    context-path: /Scau-BookShop/
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:config/mybatis-config.xml
#spring:
#  rabbitmq: # RabbitMQ配置
#    host: 127.0.0.1
#    port: 15672
#    username: guest
#    password: guest
#  data: #连接认证mongodb
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/dbName

    
#      uri: mongodb://root:123456@127.0.0.1:27017/dbName
#logging:
#  config: classpath:config/logback-web.xml #logback配置文件